# Generated by Django 3.2.8 on 2022-07-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Companies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Departure_Time', models.DateTimeField()),
                ('Landing_Time', models.DateTimeField()),
                ('Remaining_Tickets', models.IntegerField()),
                ('Airline_Company_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.airline_companies')),
                ('Destination_Country_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destination_Country_Id', to='base.countries')),
                ('Origin_Country_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countries')),
            ],
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User_Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user_roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.TextField(max_length=50)),
                ('Last_Name', models.TextField(max_length=50)),
                ('Adress', models.TextField(max_length=100)),
                ('Phone_NU', models.TextField(max_length=12, unique=True)),
                ('Credit_Card_Nu', models.TextField(max_length=16, unique=True)),
                ('User_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users')),
            ],
        ),
        migrations.AddField(
            model_name='airline_companies',
            name='Country_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countries'),
        ),
        migrations.AddField(
            model_name='airline_companies',
            name='User_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users'),
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_Name', models.TextField(max_length=50)),
                ('Last_Name', models.TextField(max_length=50)),
                ('User_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.users')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Customer_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customers')),
                ('Flight_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.flights')),
            ],
            options={
                'unique_together': {('Customer_Id', 'Flight_Id')},
            },
        ),
    ]
