# Generated by Django 3.2.8 on 2022-08-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrators',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='administrators',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='administrators',
            old_name='User_Id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='airline_companies',
            old_name='Country_Id',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='airline_companies',
            old_name='User_Id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Credit_Card_Nu',
            new_name='credit_card_nu',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Phone_NU',
            new_name='phone_nu',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='User_Id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Airline_Company_Id',
            new_name='airline_company_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Destination_Country_Id',
            new_name='destination_country_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Landing_Time',
            new_name='landing_time',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Origin_Country_Id',
            new_name='origin_country_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Remaining_Tickets',
            new_name='remaining_tickets',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='Customer_Id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='Flight_Id',
            new_name='flight_id',
        ),
        migrations.RenameField(
            model_name='user_roles',
            old_name='Role_Name',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='User_Role',
            new_name='user_role',
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('customer_id', 'flight_id')},
        ),
    ]
