# Generated by Django 3.2.8 on 2022-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='landing_time',
            field=models.DateTimeField(),
        ),
    ]
