# Generated by Django 4.0.5 on 2022-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221018_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
