# Generated by Django 3.2.8 on 2022-08-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220807_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='landing_time',
        ),
    ]
