# Generated by Django 3.2.8 on 2023-05-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_flights_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_companies',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.countries'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airline_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.airline_companies'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='destination_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_Country_Id', to='base.countries'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.countries'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customers'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flights'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user_roles'),
        ),
    ]
